language: node_js
env:
- PKG_CACHE_PATH=$HOME/pkg-cache
node_js:
- '10'
script: yarn build
cache:
  yarn: true
  directories: 
  - $PKG_CACHE_PATH
deploy:
  provider: releases
  api_key:
    secure: bbwPeImsg9sujSD5DcxCLr+eslZ51JCrAx8dzLpsm1/ivLHFRM3mXksGNrKziPfVTkk2zOVbnnyP49qRWcn/dBWFViEqFjhIoIDRhtHhPbhrDL0ecvbPwi67VOA3YGXvTk7N3BUzLKoAKKrUNyPVXmIB84sKV6TDEeYjrncLUzBth0Lw7fZN10Lmlx1KBTPcSVwlzDXtSRawp9CtGDYdJ18agnOuz7K3BIUOZQiAGJuDiNvx0eQROgczggxCJgeSd1iMKGGSHywaOQlYpeGtC98UQIz73z5hfLIQaSwjkgMfmxAEw37mSYnkCgcncXaalw06jLZ4RlEbfSNIgxGXzn0gjy+q6j9pPLiwFGNgES4+LNaDrHx2V/p7wgEkzR/BtkOO3IL3HZ5Tw3yzx1EKKG4cjhfNXu0Xup2m2io+NgsqgXTqm8sLUu3R9/qqdE2KLMe/hQSi55uDLDVs4I1ARHwa9qckMYkHS5eG6kMEcKkvhAoeY4oUIFboKWVEV/SXr4xzfQfd84TN044JxP5d0g4+Xrv+3KM0+vv406JNR4Zb3Dut2aBSgoo/63pRnTCEC6pERY3CcYnRxJcWNxNGRBMN/a0qhE5AsWZudEC1KKDdddRsjh5BP6qnOZIvKrJH69Opt1LdThbb2Zxv/WYXokvKM+4VDDOpIFHici+TGvg=
  file: 
  - "./dist/fetchbot-macos"
  - "./dist/fetchbot-linux"
  - "./dist/fetchbot-windows"
  on:
    repo: njlr/fetchbot
    tags: true
